version: 2.0

workflows:
  build:
    name: Build Android Native App

    environment:
      # Use a predefined environment image for Android
      image: codemagic/android:latest

    scripts:
      - name: Checkout code
        script: |
          git clone https://github.com/com.agusdev/your-project.git
          cd your-project

      - name: Install dependencies
        script: |
          # Install dependencies if needed
          ./gradlew dependencies

      - name: Build APK
        script: |
          # Build the APK with the release variant
          ./gradlew assembleRelease

      - name: Run Tests
        script: |
          # Run unit tests and instrumentation tests
          ./gradlew test
          ./gradlew connectedAndroidTest

    artifacts:
      - build/outputs/apk/release/app-release.apk
      - build/outputs/apk/debug/app-debug.apk

    triggers:
      # Define triggers for workflow execution
      push:
        branches:
          only:
            - main

    # Optionally, you can add deployment steps if required
    # For example, deployment to Firebase or other services
